Repository dakrone/clj-http, pull requests merged in 2018-02, with the labels that each got.

#433 Add options for how to flatten/encode form and query parameters
  README.org
  changelog.org
  src/clj_http/client.clj
  test/clj_http/test/client_test.clj
Labels: 3.x, 4.x, bug, enhancement

#434 Add ability to specify arbitrary functions to modify http client builders
  README.org
  changelog.org
  src/clj_http/client.clj
  src/clj_http/core.clj
  test/clj_http/test/core_test.clj
Labels: 3.x, 4.x, feature

#432 Multipart async
  test-resources/m.txt
  test/clj_http/test/client_test.clj
Labels: 3.x, 4.x, bug

#435 Fix redirects to an empty location
  README.org
  src/clj_http/core.clj
  test/clj_http/test/core_test.clj
Labels: 3.x, 4.x, bug
